/* This file was generated by https://github.com/dested/serverless-client-builder */
/* tslint:disable */

export class ValidationError extends Error {
  isValidationError = true;
  constructor(public model: string, public reason: 'missing' | 'mismatch' | 'too-many-fields', public field: string) {
    super();
  }
}

export class RequestModelValidator {
  static validateHiRequest(model: import('../controllers/mainController/models').HiRequest): boolean {
    let fieldCount = 0;
    if (model === null) throw new ValidationError('HiRequest', 'missing', '');
    if (typeof model !== 'object') throw new ValidationError('HiRequest', 'mismatch', '');

    if (Object.keys(model).length !== fieldCount) throw new ValidationError('HiRequest', 'too-many-fields', '');

    return true;
  }
}
